name: Checking Tests
#Test 3
on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Checking tests
    runs-on: ubuntu-latest

    services: 
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm install 

      - name: Install concurrently
        run: npm install -g concurrently

      - name: Build App
        run: npm run build

      - name: Seed Database
        run: npm run seed

      - name: Start Server
        run: npm start &

      - name: Wait for Server to Start
        run: npx wait-on http://localhost:3000

      - name: Run Component Tests
        run: npm run test-component