name: Deploy To Render

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start server
        run: npm start &

      - name: Wait for server to be ready
        run: wait-on http://localhost:3001 --timeout 30000

      - name: Check server logs
        run: |
          sleep 5
          curl -I http://localhost:3001

      - name: Run Cypress tests
        run: npx cypress run --browser electron

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"