name: Deploy To Render

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

         - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$deploy_url"